.TH THUNAR-VOLMAN-SETTINGS "1" "August 2013" "thunar-volman-settings" "User Commands"
.SH NAME
thunar-volman-settings \- controls configuration of thunar's removable media
.SH NOTE
Note that usually this command is invoked by thunar itself and you should
only use this if you are having problems adding the device as per the
documentation cited at the end of this manpage.
.SH DESCRIPTION
.SS "Usage:"
.IP
thunar\-volman\-settings [OPTION...]
.SS "Help Options:"
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
\fB\-\-help\-gtk\fR
Show GTK+ Options
.PP
GTK+ Options
.TP
\fB\-\-class\fR=\fICLASS\fR
Program class as used by the window manager
.TP
\fB\-\-name\fR=\fINAME\fR
Program name as used by the window manager
.TP
\fB\-\-screen\fR=\fISCREEN\fR
X screen to use
.TP
\fB\-\-sync\fR
Make X calls synchronous
.TP
\fB\-\-gtk\-module\fR=\fIMODULES\fR
Load additional GTK+ modules
.TP
\fB\-\-g\-fatal\-warnings\fR
Make all warnings fatal
.SS "Application Options:"
.TP
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use
.SH AUTHOR
Written by Benedikt Meurer <benny@xfce.org>.
.PP
This manual page was written by Jackson Doak <noskcaj@ubuntu.com> (with
help from help2man) for the Debian project but may be used by others.
.PP
Please report bugs to Debian's bug tracking system.  Details can be found at
http://bugs.debian.org/
.SH COPYRIGHT
Copyright \(co 2004-2013
        The Thunar development team. All rights reserved.
.SH "SEE ALSO"
The full documentation for
.B thunar-volman-settings
is maintained in /usr/share/doc/thunar/html/C/using-removable-media.html